### ISSUE TITLE
Manual how to use with scry?

### ISSUE THREAD

**Issue by idchlife** [faustinoaq/vscode-crystal-lang#12]
I cloned scry repo, build scry executable from src/scry and wrote path to this executable in settings (for scry binary)

But it seems that server does not work.

Am I doing it wrong?

**Comment by faustinoaq** [comment]
Scry is experimental. but should works well.

Can you show me your `settings.json`?

You can ensure that scry works opening a new tab as an Untitled Crystal document and then writing some code, you should notice the syntax errors are detected, because Scry have live Diagnostics.

![screenshot_20170805_062844](https://user-images.githubusercontent.com/3067335/28995174-55cd7382-79a7-11e7-8c4b-d73de7536c5f.png)

**Comment by idchlife** [comment]
@faustinoaq I recorder the video me checking it out https://monosnap.com/file/PwKIcY9otrJz7ccoJkmNcWbWl1rCdO

Thanks for helping with this one out!

**Comment by idchlife** [comment]
Woooooow.... I used path to directory, executable is in upper dir.

It seems my mistake.

Server started but with error:

![image](https://user-images.githubusercontent.com/4563032/28995241-e01a3864-79ec-11e7-8b6f-7036aaeab709.png)

**Comment by idchlife** [comment]
I fixed it. Guess problem with scry config or something, it writes to /.scry.out path, thinking Dir.current is /

Thanks!

**Comment by doughsay** [comment]
@idchlife how did you fix that error?  I'm getting the same error now too...

![image](https://user-images.githubusercontent.com/221693/29103676-eda577d8-7c75-11e7-8270-90ddb635116a.png)

**Comment by idchlife** [comment]
Added .scry.out file into / with read write rights :D

**Comment by doughsay** [comment]
> Added .scry.out file into / with read write rights :D

lol! hilarious...

**Comment by doughsay** [comment]
@idchlife see this issue I just opened: https://github.com/faustinoaq/vscode-crystal-lang/issues/14

If you launch vscode from shell using the `code` helper, it works.
